---
server:
  port: 9090
  contextPath: /
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ikebana
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    schema:
    maxConnections: 300
    initialConnections: 20
    maxAge: 30000
    testOnBorrow: true
    testWhileIdle:  true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    minPoolSize: 6
    maxPoolSize: 15
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#          TODO check ddl configuration
          ddl-auto: update
